@startuml

skinparam RoundCorner 20
skinparam MaxMessageSize 300
skinparam NoteBackgroundColor LightGreen
skinparam NoteBorderColor SteelBlue
skinparam DefaultFontName Fira Code

skinparam sequence {
  BackgroundColor AliceBlue
  BorderColor SteelBlue

  lifeline {
    BackgroundColor OldLace
    BorderColor SteelBlue
  }
  actor {
    BackgroundColor LightYellow
    BorderColor SteelBlue
  }
  participant {
    BackgroundColor AliceBlue
    BorderColor SteelBlue
  }
  box {
    BackgroundColor LightYellow
    BorderColor SteelBlue
  }
  arrow {
    Color RoyalBlue
    Thickness 2
  }
}

title = **URL Shortener Design 1**

actor User
participant App
participant DB

User -> App: Request long url to be made short
note right User
http://longurl.com/
endnote

App -> App: Generate unique id
App -> App: Map and encode key to a storable id
note right App
hashid(123456) = xkNDJ
end note
App -> DB: Store record
note right App
{
  id: 123456
  url: http://longurl.com/
}
endnote

note right DB #LightBlue
| id     | url                 |
| 123456 | http://longurl.com/ |
endnote

DB --> App: OK
App -> User: Return short url
note left App
http://sho.rt/xkNDJ
endnote

@enduml
